// Our own step-by-step instructions for catalog entries that take their photos from free-exercise-db.
// free-exercise-db's instruction text was copied from a commercial site, so it is never used; entries
// written for this project keep their instructions in curation.ts.
export const INSTRUCTIONS: Record<string, string[]> = {
  'smith-machine-squat': [
    'Set the bar at shoulder height, step under it so it rests across your upper back, and place your feet slightly ahead of the bar.',
    'Unhook the bar by twisting it, take a breath and brace your midsection.',
    'Bend your knees and hips to sit straight down until your thighs are about parallel, knees following your toes.',
    'Push through your whole foot to stand back up, then twist the bar back onto the hooks when the set is done.',
  ],
  'leg-press': [
    'Sit in the machine with your back and hips flat against the pad, feet hip width in the middle of the platform.',
    'Release the safety handles and bend your knees, lowering the platform until your knees come close to your chest.',
    'Push the platform away through your whole foot, keeping your lower back pressed into the pad.',
    'Stop just short of locking your knees, then start the next rep. Reset the safeties when you finish.',
  ],
  'hack-squat': [
    'Step onto the platform with feet shoulder width, shoulders under the pads and your back flat against the backrest.',
    'Release the safety handles and bend your knees to lower yourself as deep as you can control.',
    'Press through the middle of your feet to straighten your legs, keeping your hips on the pad.',
    'Stop just short of locking your knees, then lower for the next rep. Reset the safeties when you finish.',
  ],
  'smith-romanian-deadlift': [
    'Set the bar at mid-thigh height, grip it just outside your legs, and unhook it standing tall with feet hip width.',
    'Unlock your knees slightly and send your hips back, letting the bar slide down along your thighs.',
    'Lower until you feel a strong pull in your hamstrings, keeping your back flat the whole way.',
    'Drive your hips forward to stand back up, squeezing your glutes at the top.',
  ],
  'cable-pull-through': [
    'Set a rope on a low pulley, face away from the stack and grab the rope between your legs, then step forward until the cable is tight.',
    'Stand with feet a little wider than hips, then push your hips back and let your arms hang as the rope travels between your legs.',
    'Drive your hips forward to stand tall, squeezing your glutes hard at the top.',
    'Hinge back again under control, keeping your back flat and knees softly bent.',
  ],
  'dumbbell-split-squat': [
    'Hold a dumbbell in each hand at your sides and set a long split stance, both feet facing forward.',
    'Bend both knees to sink straight down until your back knee is just above the floor.',
    'Press through your front heel to rise back up, keeping your torso upright.',
    'Complete all reps on this leg, then switch your stance and repeat on the other side.',
  ],
  'dumbbell-reverse-lunge': [
    'Stand tall with feet hip width, a dumbbell hanging at each side.',
    'Take a long step straight back with one foot and lower until the back knee is just above the floor.',
    'Keep the front knee over the middle of the foot and your chest upright as you descend.',
    'Push through the front heel to bring the back foot forward to standing, then step back with the other leg.',
  ],
  'dumbbell-step-up': [
    'Stand facing a bench holding a dumbbell in each hand, arms straight at your sides.',
    'Place one whole foot on the bench, then press through that heel to step up until you stand tall on top.',
    'Step the trailing foot down slowly, keeping your weight on the working leg as you lower.',
    'Keep the same leg on the bench for the set, then switch sides.',
  ],
  'leg-extension': [
    'Sit with your back against the pad and adjust the seat so your knees line up with the machine\'s pivot point.',
    'Hook the roller pad just above your ankles and hold the side handles.',
    'Straighten your legs to lift the pad, then hold the top briefly while tightening your thighs.',
    'Bend your knees slowly to lower the weight back down without letting the stack touch.',
  ],
  'single-leg-extension': [
    'Sit on the machine with your back against the pad and one ankle behind the roller, knee lined up with the pivot.',
    'Hold the handles and straighten that leg until it is fully extended, keeping your hips down on the seat.',
    'Pause briefly at the top, then lower the weight slowly until the knee is bent again.',
    'Finish the set, then switch legs and do the same number of reps.',
  ],
  'seated-leg-curl': [
    'Sit in the machine with the backs of your ankles on the lower pad and lock the thigh pad down snugly.',
    'Line your knees up with the machine\'s pivot and hold the side handles.',
    'Bend your knees to pull the pad down and back as far as it will go.',
    'Let the pad rise slowly until your legs are nearly straight, then repeat.',
  ],
  'lying-leg-curl': [
    'Lie face down on the machine with the roller pad resting just above your heels and your knees just off the bench edge.',
    'Hold the handles and keep your hips pressed down into the pad.',
    'Bend your knees to pull the pad up toward your glutes as far as you can.',
    'Straighten your legs slowly to lower the pad, keeping tension the whole way down.',
  ],
  'standing-calf-raise': [
    'Step under the shoulder pads with the balls of your feet on the platform edge and your heels hanging off.',
    'Stand tall with straight legs and let your heels sink until you feel a full stretch in your calves, then pause.',
    'Press up onto your toes as high as you can, pushing through the big toe side of your feet.',
    'Lower slowly back into the stretch without bouncing, and repeat.',
  ],
  'seated-calf-raise': [
    'Sit on the machine with the balls of your feet on the platform edge and the pad resting just above your knees.',
    'Lift the pad slightly and release the safety lever, then let your heels drop into a deep stretch.',
    'Pause briefly at the bottom, then press up onto the balls of your feet as high as you can.',
    'Lower back to the stretch slowly. Re-engage the safety lever when the set is done.',
  ],
  'smith-machine-calf-raise': [
    'Set a weight plate under the bar and stand with the balls of your feet on its edge, bar across your upper back.',
    'Unhook the bar and let your heels drop below the plate for a full stretch, knees straight.',
    'Rise up onto your toes as high as you can and pause briefly at the top.',
    'Lower your heels slowly back into the stretch. Rack the bar when the set is done.',
  ],
  'back-extension': [
    'Set the pad so it sits just below your hip crease, then lock your heels under the foot rollers.',
    'Cross your arms over your chest and bend forward at the hips, keeping your back flat.',
    'Squeeze your glutes to raise your torso until your body forms a straight line, without arching past it.',
    'Lower back down under control and repeat.',
  ],
  'glute-bridge': [
    'Lie on your back with knees bent, feet flat on the floor close to your glutes, and arms by your sides.',
    'Brace your stomach so your ribs stay down, then press through your heels to lift your hips.',
    'Rise until your body forms a straight line from knees to shoulders and squeeze your glutes for two seconds.',
    'Lower your hips slowly back to the floor and repeat.',
  ],
  'single-leg-glute-bridge': [
    'Lie on your back with one knee bent and that foot flat, the other leg straight out or tucked toward your chest.',
    'Push through the heel of your planted foot to lift your hips off the floor.',
    'Pause at the top with your hips level and your glute squeezed.',
    'Lower your hips back down slowly. Finish the set, then switch legs.',
  ],
  'hip-adduction-machine': [
    'Sit in the machine with your back against the pad and the pads resting on the inside of your knees.',
    'Set the starting width so your legs are open to a comfortable stretch, and hold the handles.',
    'Squeeze your legs together until the pads meet, pausing briefly.',
    'Let your legs open slowly back to the start, keeping the weight from crashing down.',
  ],
  'cable-hip-adduction': [
    'Strap the ankle nearest a low pulley, then step out sideways until the cable pulls that leg out to the side.',
    'Hold the tower with one hand and stand tall on your outside leg.',
    'Pull the strapped leg across in front of your standing leg, keeping your torso still.',
    'Let the leg return out to the side under control. Finish the set, then switch sides.',
  ],
  'hip-abduction-machine': [
    'Sit in the machine with the pads against the outsides of your knees and hold the handles.',
    'Sit tall or tip slightly forward from the hips, feet resting on the foot bars.',
    'Press your knees outward against the pads as far as you comfortably can.',
    'Let the pads come back together slowly without letting the weight stack rest.',
  ],
  'smith-bench-press': [
    'Set a flat bench under the bar so it lines up with your mid-chest, then lie down with feet flat on the floor.',
    'Pinch your shoulder blades together, grip the bar a little wider than your shoulders, and twist it off the hooks.',
    'Lower the bar under control until it touches your chest, elbows angled slightly in from your sides.',
    'Press back up to straight arms, then twist the bar onto the hooks when the set is done.',
  ],
  'dumbbell-bench-press': [
    'Sit on the end of a flat bench with dumbbells on your thighs, then lie back and use your knees to bring them up over your chest.',
    'Lower the dumbbells to the sides of your chest, elbows angled about 45 degrees from your body.',
    'Press them back up and slightly toward each other until your arms are straight over your chest.',
    'Lower again under control, and when finished bring the dumbbells back to your knees before sitting up.',
  ],
  'machine-chest-press': [
    'Adjust the seat so the handles sit level with the middle of your chest, then sit with your back flat on the pad.',
    'Grip the handles and pull your shoulder blades back into the seat.',
    'Push the handles forward until your arms are nearly straight, without slamming your elbows into lockout.',
    'Bring the handles back slowly until you feel a stretch across your chest.',
  ],
  'smith-close-grip-bench-press': [
    'Lie on a flat bench under the bar with feet planted, and grip the bar with hands about shoulder width apart.',
    'Set your shoulder blades back and twist the bar off the hooks.',
    'Lower the bar to your lower chest, keeping your elbows tucked close to your body.',
    'Press up until your arms are straight, then rack the bar when the set is done.',
  ],
  'incline-dumbbell-press': [
    'Set the bench to a low incline, sit back with a dumbbell on each thigh, and kick them up to shoulder level as you lie back.',
    'Lower the dumbbells to the sides of your upper chest with your feet planted and shoulder blades pulled back.',
    'Press up until your arms are straight above your collarbones.',
    'Lower under control for the next rep, then return the dumbbells to your thighs when finished.',
  ],
  'smith-incline-bench-press': [
    'Set an incline bench under the Smith bar so the bar lines up with your upper chest, then lie back.',
    'Grip the bar slightly wider than shoulder width, pull your shoulder blades down and back, and unhook it.',
    'Lower the bar under control until it lightly touches your upper chest.',
    'Press it back up until your arms are straight, then twist the bar to rack it after the last rep.',
  ],
  'incline-neutral-grip-dumbbell-press': [
    'Set a bench to a low incline and sit back with a dumbbell in each hand, resting on your thighs.',
    'Lie back and bring the dumbbells up beside your chest, palms facing each other and elbows close to your sides.',
    'Press the dumbbells up until your arms are straight over your upper chest, squeezing your chest at the top.',
    'Lower them slowly back to the sides of your chest and repeat.',
  ],
  'incline-push-up': [
    'Place your hands on the edge of a bench slightly wider than your shoulders and walk your feet back.',
    'Brace so your body forms a straight line from head to heels.',
    'Bend your elbows to lower your chest to the bench edge, elbows angled back slightly.',
    'Push the bench away to straighten your arms, keeping your hips in line.',
  ],
  'push-up': [
    'Start in a high plank with your hands under your shoulders and your body in a straight line from head to heels.',
    'Brace your core and squeeze your glutes to keep your hips from sagging.',
    'Bend your elbows to lower your chest toward the floor until it nearly touches.',
    'Push the floor away to straighten your arms and return to the plank.',
  ],
  'decline-push-up': [
    'Place your feet on a bench behind you and your hands on the floor just under your shoulders.',
    'Brace your core and glutes so your body is straight from heels to head.',
    'Bend your elbows to lower your chest close to the floor without letting your hips sag.',
    'Push the floor away until your arms are straight again, and repeat.',
  ],
  'cable-crossover': [
    'Set both pulleys high, take a handle in each hand and step forward into a staggered stance with a slight forward lean.',
    'Start with your arms out wide, elbows softly bent and chest open.',
    'Sweep the handles down and in until your hands meet in front of your hips, squeezing your chest.',
    'Let your arms open back out slowly until you feel a stretch across your chest.',
  ],
  'low-to-high-cable-fly': [
    'Set both pulleys at the lowest position, grab a handle in each hand and step forward to stand between them.',
    'Start with your arms down and slightly back, palms facing forward and elbows softly bent.',
    'Sweep both hands up and together in an arc until they meet around chin height.',
    'Lower your arms back down and out along the same path, under control.',
  ],
  'pec-deck': [
    'Adjust the seat so the handles line up with your chest, then sit with your back flat against the pad.',
    'Take the handles with a slight bend in your elbows, chest lifted and shoulders pulled back.',
    'Bring your arms together in a wide arc until the handles meet in front of your chest, then squeeze.',
    'Let your arms open slowly back to the start, stopping at a comfortable stretch.',
  ],
  'dumbbell-fly': [
    'Lie on a flat bench and hold the dumbbells above your chest, palms facing each other and elbows slightly bent.',
    'Open your arms out to the sides in a wide arc until you feel a stretch in your chest.',
    'Keep the elbow bend fixed and bring the dumbbells back up along the same arc.',
    'Stop when they are over your chest, then lower for the next rep.',
  ],
  'dumbbell-curl': [
    'Stand tall holding a dumbbell in each hand, arms straight at your sides and palms facing forward.',
    'Keeping your elbows tight to your sides, curl the weights up toward your shoulders.',
    'At the top, rotate your wrists a little so your little fingers turn upward, and squeeze.',
    'Lower the dumbbells slowly to full arm length without swinging.',
  ],
  'cable-curl': [
    'Attach a straight bar to a low pulley, grip it palms up at shoulder width, and step back so the cable stays tight.',
    'Stand tall with your elbows pinned at your sides.',
    'Curl the bar up toward your shoulders, squeezing your biceps at the top.',
    'Lower slowly until your arms are straight, keeping tension on the cable.',
  ],
  'machine-preacher-curl': [
    'Adjust the seat so your armpits rest snugly on the top of the pad and your arms lie flat down it.',
    'Grip the handles with palms up and arms nearly straight.',
    'Curl the handles up toward your shoulders as far as they will go.',
    'Lower slowly, stopping just short of full relaxation at the bottom before the next rep.',
  ],
  'dumbbell-preacher-curl': [
    'Set an adjustable bench upright and stand behind it, resting the back of one arm flat on the backrest, dumbbell in hand.',
    'Curl the dumbbell up toward your shoulder, keeping your upper arm on the pad.',
    'Lower it slowly until your arm is almost straight, stopping just short of locking out.',
    'Finish all reps on this arm, then switch to the other side.',
  ],
  'spider-curl': [
    'Set a bench to an incline and lie chest down on it, a dumbbell in each hand with arms hanging straight down.',
    'Keep your upper arms pointing straight at the floor and palms facing forward.',
    'Curl the dumbbells up toward your shoulders without letting your elbows drift, and squeeze hard at the top.',
    'Lower them slowly until your arms are straight again.',
  ],
  'concentration-curl': [
    'Sit on the end of a bench with feet wide and hold a dumbbell in one hand.',
    'Lean forward and brace the back of that elbow against your inner thigh, arm hanging straight.',
    'Curl the dumbbell up toward your opposite shoulder and pause briefly at the top.',
    'Lower it slowly until your arm is straight. Finish the set, then switch sides.',
  ],
  'incline-dumbbell-curl': [
    'Set a bench to a 45 to 60 degree incline and sit back with a dumbbell in each hand, arms hanging straight down.',
    'Keep your elbows pointed down and slightly behind your body throughout.',
    'Curl both dumbbells up toward your shoulders without letting your elbows drift forward.',
    'Lower them all the way until your arms are fully straight and you feel a stretch.',
  ],
  'hammer-curl': [
    'Stand tall holding a dumbbell at each side, palms facing your legs.',
    'Keep your elbows tucked at your sides and your thumbs pointing up.',
    'Curl the dumbbells up toward your shoulders without turning your wrists.',
    'Lower them slowly back down until your arms are straight.',
  ],
  'cross-body-hammer-curl': [
    'Stand tall holding a dumbbell in each hand at your sides, palms facing your legs.',
    'Keeping your palm facing in, curl one dumbbell up and across toward the opposite side of your chest.',
    'Lower it under control along the same path while your upper arm stays still.',
    'Repeat with the other arm, alternating sides each rep.',
  ],
  'rope-hammer-curl': [
    'Attach a rope to the low pulley and hold an end in each hand, palms facing each other, standing close to the stack.',
    'Pin your elbows at your sides and curl the rope up toward your shoulders.',
    'At the top, spread the rope ends apart slightly and squeeze.',
    'Lower the rope slowly until your arms are straight again.',
  ],
  'incline-hammer-curl': [
    'Sit back on a bench set to a moderate incline, a dumbbell in each hand with arms hanging straight down.',
    'Turn your palms to face your body so your thumbs point forward.',
    'Curl the dumbbells up toward your shoulders, keeping your thumbs up and upper arms still.',
    'Lower slowly until your arms are fully straight and you feel a stretch, then repeat.',
  ],
  'reverse-cable-curl': [
    'Attach a straight bar to a low pulley and hold it with an overhand grip, hands about shoulder width.',
    'Stand tall with your elbows at your sides and wrists straight.',
    'Curl the bar up toward your shoulders without letting your elbows drift forward.',
    'Lower it slowly until your arms are straight, keeping tension on the cable.',
  ],
  'reverse-dumbbell-curl': [
    'Stand holding a dumbbell in each hand with your palms facing behind you, arms straight at your sides.',
    'Keep your wrists straight and your elbows close to your body.',
    'Curl the dumbbells up toward your shoulders, keeping your palms down the whole way.',
    'Lower them slowly back to your thighs.',
  ],
  'zottman-curl': [
    'Stand tall with a dumbbell at each side, palms facing forward.',
    'Curl the dumbbells up to your shoulders, keeping your elbows at your sides.',
    'At the top, rotate your wrists so your palms face down.',
    'Lower the dumbbells slowly with palms down, then turn them back up at the bottom for the next rep.',
  ],
  'wide-grip-lat-pulldown': [
    'Grip the long bar well outside shoulder width with palms facing away, then sit with your thighs locked under the pads.',
    'Lean back slightly and pull the bar down to your upper chest, driving your elbows down and back.',
    'Squeeze your shoulder blades together briefly at the bottom.',
    'Let the bar rise slowly until your arms are straight and your lats are stretched.',
  ],
  'close-grip-lat-pulldown': [
    'Attach a close neutral grip handle, sit with your thighs under the pads and reach up to grab it.',
    'Let your arms straighten fully overhead so you feel a stretch through your back.',
    'Lift your chest and pull the handle down toward your upper chest, driving your elbows down and back.',
    'Let the handle rise slowly until your arms are straight again.',
  ],
  'underhand-lat-pulldown': [
    'Sit at the pulldown station with your thighs under the pads and grab the bar palms toward you, hands shoulder width.',
    'Lean back just slightly and lift your chest.',
    'Pull the bar down to your upper chest by driving your elbows down and back, keeping your torso still.',
    'Let the bar rise slowly until your arms are straight overhead, and repeat.',
  ],
  'single-arm-cable-pulldown': [
    'Set a single handle on a high pulley and sit or kneel facing it, holding the handle in one hand with your arm reaching up.',
    'Let your shoulder lift to stretch your lat, keeping your torso square.',
    'Pull your elbow down toward your hip without twisting.',
    'Return the handle up slowly until your arm is fully extended. Finish the set, then switch sides.',
  ],
  'chin-up': [
    'Grab the bar with your palms facing you, hands about shoulder width, and hang with your arms straight.',
    'Pull your shoulders down, then pull yourself up by driving your elbows toward your ribs.',
    'Keep going until your chin clears the bar.',
    'Lower yourself slowly back to a full hang before the next rep.',
  ],
  'pull-up': [
    'Grab the bar with palms facing away, hands a little wider than your shoulders, and hang with straight arms.',
    'Pull your shoulders down and back, then drive your elbows toward your ribs.',
    'Pull until your chin clears the bar, without swinging or kicking.',
    'Lower yourself under control all the way back to a dead hang.',
  ],
  'seated-cable-row': [
    'Sit at the row station with feet on the platform, knees slightly bent, and grab the handle with arms straight.',
    'Sit tall and pull the handle toward your belly button, drawing your shoulder blades together.',
    'Hold the squeeze briefly with your chest up and torso still.',
    'Extend your arms slowly and let your shoulders reach forward before the next rep.',
  ],
  'one-arm-dumbbell-row': [
    'Place one knee and the same side hand on a flat bench, back flat, and hold a dumbbell in your other hand.',
    'Let the dumbbell hang straight down so you feel a stretch through your side.',
    'Pull the dumbbell up toward your hip, keeping your elbow close to your body.',
    'Lower it slowly back to the stretch. Finish the set, then switch sides.',
  ],
  'chest-supported-dumbbell-row': [
    'Set a bench to a low incline and lie chest down on it, a dumbbell in each hand hanging below your shoulders.',
    'Keep your chest on the pad and your neck in line with your spine.',
    'Row the dumbbells up by driving your elbows back and up, squeezing your shoulder blades together.',
    'Lower them slowly until your arms are straight, and repeat.',
  ],
  'smith-bent-over-row': [
    'Set the bar at about knee height, grip it slightly wider than shoulders with palms down, and unhook it.',
    'Hinge at the hips until your torso is about 45 degrees, back flat and knees slightly bent.',
    'Pull the bar up to your lower ribs, keeping your hips still.',
    'Lower it until your arms are straight, then re-hook the bar when the set is done.',
  ],
  'machine-row': [
    'Set the seat so the handles are at mid-chest height and sit with your chest against the pad.',
    'Grab the handles with your arms extended forward.',
    'Pull the handles toward you by driving your elbows back, then hold briefly with your shoulder blades squeezed.',
    'Let your arms extend slowly back to the start.',
  ],
  'inverted-row': [
    'Set the bar at about hip height, lie underneath it, and grip it slightly wider than your shoulders.',
    'Straighten your body from heels to head with your heels on the floor and arms fully extended.',
    'Pull your chest up to the bar, keeping your hips from sagging.',
    'Lower yourself slowly until your arms are straight. Raise the bar to make it easier.',
  ],
  'straight-arm-pulldown': [
    'Attach a straight bar or rope to a high pulley, grip it about shoulder width and step back.',
    'Hinge forward slightly with arms nearly straight and the bar at about eye level.',
    'Sweep the bar down in an arc to your thighs, keeping your elbows fixed and feeling your lats work.',
    'Let it rise back up slowly until you feel a stretch under your arms.',
  ],
  'dumbbell-pullover': [
    'Lie on a flat bench and hold one dumbbell above your chest with both hands cupping the top end.',
    'Keeping a slight bend in your elbows, lower the dumbbell back behind your head until you feel a stretch.',
    'Pull it back up and over your chest by using your lats.',
    'Stop with the dumbbell above your chest, then repeat.',
  ],
  'dumbbell-shrug': [
    'Stand tall with a dumbbell at each side, palms facing your legs.',
    'Lift your shoulders straight up toward your ears, keeping your arms straight.',
    'Hold the top for a moment without rolling your shoulders.',
    'Lower your shoulders slowly back down and repeat.',
  ],
  'smith-machine-shrug': [
    'Set the bar at mid thigh height, stand with your back to it and grip it behind you, hands about shoulder width.',
    'Unhook the bar and stand tall with it resting just behind your thighs, arms straight.',
    'Shrug your shoulders up and slightly back, holding for a second at the top.',
    'Lower your shoulders slowly to the start, then re-hook the bar when finished.',
  ],
  'cable-shrug': [
    'Attach a straight bar to a low pulley and stand close to the stack holding the bar in front of your thighs.',
    'Keep your arms straight and your body upright.',
    'Lift your shoulders straight up toward your ears and squeeze at the top.',
    'Lower your shoulders slowly back down to a full stretch.',
  ],
  'smith-overhead-press': [
    'Set an upright bench under the bar so the bar passes just in front of your face, then sit with feet planted.',
    'Grip the bar slightly wider than your shoulders and twist it off the hooks.',
    'Lower the bar to about chin height, then press it straight up until your arms lock out, head moving forward under it.',
    'Lower back to chin height for the next rep, and twist the bar onto the hooks when done.',
  ],
  'seated-dumbbell-shoulder-press': [
    'Set a bench upright, sit with your back flat against it and bring the dumbbells to ear height, palms forward.',
    'Brace your stomach and plant your feet on the floor.',
    'Press the dumbbells straight up until your arms are extended, without knocking them together.',
    'Lower them back to ear height under control for the next rep.',
  ],
  'machine-shoulder-press': [
    'Set the seat so the handles start at shoulder height and sit with your back flat on the pad.',
    'Grab the handles with your elbows below your hands.',
    'Press the handles overhead until your arms are almost straight, keeping your shoulders down away from your ears.',
    'Lower the handles slowly back to shoulder height.',
  ],
  'arnold-press': [
    'Sit on an upright bench holding the dumbbells in front of your chin, palms facing you.',
    'Press the dumbbells up while turning your palms to face forward.',
    'Finish with arms straight overhead and palms forward.',
    'Reverse the motion on the way down, turning your palms back toward you as they reach chin height.',
  ],
  'dumbbell-lateral-raise': [
    'Stand tall with a dumbbell in each hand at your sides, elbows slightly bent.',
    'Lead with your elbows and raise your arms out to the sides.',
    'Stop when your arms reach shoulder height, reaching out rather than up.',
    'Lower them slowly back to your sides.',
  ],
  'cable-lateral-raise': [
    'Set a pulley at the lowest position and stand side on to it, holding the handle in your far hand.',
    'Let the cable cross in front of or behind your body, with a slight bend in your elbow.',
    'Raise your arm out to the side until your hand reaches shoulder height.',
    'Lower it slowly back down. Complete the set, then switch sides.',
  ],
  'incline-side-lying-lateral-raise': [
    'Set a bench to a low incline and lie on your side against it, a dumbbell in your top hand.',
    'Let the dumbbell hang down across the front of your body with a slight bend in the elbow.',
    'Raise the arm out and up until it points straight at the ceiling, then lower it slowly.',
    'Finish the set, then turn over and switch arms.',
  ],
  'face-pull': [
    'Set a rope on a pulley at face height, grip both ends with thumbs toward you and step back until your arms are straight.',
    'Stand tall and pull the rope toward your eyes, elbows high and out to the sides.',
    'Pull the rope ends apart so your hands finish beside your ears with thumbs pointing behind you.',
    'Let your arms extend back to the start under control.',
  ],
  'reverse-pec-deck': [
    'Sit facing the machine with your chest against the pad and set the handles to the rear position.',
    'Grab the handles with your arms out in front at shoulder height and elbows slightly bent.',
    'Sweep your arms out and back in a wide arc, leading with the backs of your shoulders.',
    'Bring the handles forward slowly to the start without letting the stack rest.',
  ],
  'bent-over-dumbbell-rear-delt-raise': [
    'Sit on the end of a bench with a dumbbell in each hand and lean forward until your chest nears your thighs.',
    'Let the dumbbells hang beneath your legs, palms facing each other and elbows slightly bent.',
    'Raise the dumbbells out to your sides until your arms are level with your back, little fingers leading.',
    'Lower them slowly back down without swinging.',
  ],
  'overhead-cable-extension': [
    'Attach a rope to a pulley, grab it and turn to face away from the machine with the rope behind your head.',
    'Step into a staggered stance and lean forward slightly, elbows pointing forward.',
    'Straighten your arms to push the rope forward and up, keeping your elbows in place.',
    'Bend your elbows slowly to let the rope come back behind your head for a deep stretch.',
  ],
  'seated-dumbbell-overhead-extension': [
    'Sit on a bench with back support and hold one dumbbell overhead with both hands cupping the top end.',
    'Keep your elbows close together and pointing toward the ceiling.',
    'Bend your elbows to lower the dumbbell behind your head until you feel a stretch.',
    'Straighten your arms to press it back overhead.',
  ],
  'single-arm-dumbbell-overhead-extension': [
    'Sit on a bench with an upright back pad, holding a dumbbell straight overhead in one hand.',
    'Keep that upper arm close to your ear and support the elbow with your free hand.',
    'Bend the elbow to lower the dumbbell behind your head, then straighten your arm to press it back up.',
    'Finish the set, then switch arms.',
  ],
  'dumbbell-skull-crusher': [
    'Lie on a flat bench holding the dumbbells above your chest, palms facing each other, arms tilted slightly back toward your head.',
    'Bend only at the elbows to lower the dumbbells beside your ears.',
    'Straighten your arms to bring the dumbbells back up, keeping your upper arms still.',
    'Stop just before your elbows lock, then lower for the next rep.',
  ],
  'rope-pushdown': [
    'Attach a rope to a high pulley and stand facing it, holding an end in each hand with elbows at your sides.',
    'Push the rope down until your arms are straight.',
    'At the bottom, pull the rope ends apart and squeeze your triceps.',
    'Let your forearms rise slowly until your hands reach chest height, elbows still pinned.',
  ],
  'bar-pushdown': [
    'Attach a V-bar to a high pulley and grip it with palms facing each other.',
    'Lean forward slightly and pin your elbows at your sides.',
    'Push the bar down until your arms are fully straight, then squeeze your triceps.',
    'Let the bar rise slowly until your forearms are just above parallel, elbows still at your sides.',
  ],
  'reverse-grip-pushdown': [
    'Attach a straight bar to a high pulley and grip it with palms up, hands about shoulder width.',
    'Stand tall with your elbows tucked tight against your sides.',
    'Push the bar down until your arms are straight, squeezing your triceps.',
    'Let the bar rise slowly until your forearms are just above parallel to the floor.',
  ],
  'dumbbell-kickback': [
    'Support yourself with one knee and hand on a bench, holding a dumbbell in your free hand.',
    'Raise that upper arm so it sits parallel to the floor, elbow bent at about 90 degrees.',
    'Straighten your arm behind you, moving only the forearm, and squeeze at full extension.',
    'Bend your elbow slowly to return. Finish the set, then switch sides.',
  ],
  'triceps-dip-machine': [
    'Sit in the machine with your back against the pad and grip the handles at your sides.',
    'Sit tall with your shoulders down and your elbows pointing straight back.',
    'Press the handles down until your arms are fully locked out.',
    'Let the handles rise slowly until your elbows are bent about 90 degrees, and repeat.',
  ],
  'bench-dip': [
    'Sit on the edge of a bench, hands gripping the edge beside your hips, and walk your feet out.',
    'Slide your hips off the bench so they stay close to it, arms straight.',
    'Bend your elbows to lower your body until your upper arms are parallel to the floor.',
    'Press through your palms to straighten your arms and rise back up. Bend your knees to make it easier.',
  ],
  'plate-pinch': [
    'Stack two weight plates together with the smooth faces on the outside.',
    'Pinch them with your fingers on one side and thumb on the other, then lift and hold them at your side.',
    'Keep your grip tight, stand tall and breathe steadily for the whole hold.',
    'When time is up, lower the plates carefully, then switch hands.',
  ],
  'dumbbell-wrist-curl': [
    'Sit on the end of a bench with a dumbbell in each hand, forearms resting on your thighs palms up.',
    'Slide forward so your wrists hang just past your knees.',
    'Let the dumbbells roll down toward your fingertips, then curl your wrists up as high as you can.',
    'Lower slowly to the bottom again, keeping your forearms still on your thighs.',
  ],
  'cable-wrist-curl': [
    'Attach a straight bar to a low pulley and sit on a bench facing it, gripping the bar with palms up.',
    'Rest your forearms on your thighs so your wrists hang just past your knees.',
    'Curl your wrists up as high as you can without lifting your forearms.',
    'Lower the bar slowly into a stretch, keeping tension on the cable without bouncing.',
  ],
  'dumbbell-reverse-wrist-curl': [
    'Sit on a bench with your forearms resting on your thighs, palms down, wrists just past your knees with a light dumbbell in each hand.',
    'Let your hands drop toward the floor as far as is comfortable.',
    'Lift your knuckles up toward the ceiling by bending only at the wrist.',
    'Lower the dumbbells slowly back down.',
  ],
  plank: [
    'Lie face down and set your elbows under your shoulders, forearms flat on the mat.',
    'Lift your hips so your body is in a straight line from heels to head.',
    'Squeeze your glutes, pull your ribs down, and breathe steadily while you hold.',
    'Hold for the set time without letting your hips sag, then lower your knees to the mat.',
  ],
  'ab-wheel-rollout': [
    'Kneel on a mat holding the ab wheel on the floor below your shoulders.',
    'Tuck your pelvis and squeeze your glutes to lock your lower back flat.',
    'Roll the wheel forward slowly, stopping before your lower back starts to sag.',
    'Use your abs to pull the wheel back under your shoulders, without pushing your hips back first.',
  ],
  'dead-bug': [
    'Lie on your back with arms reaching toward the ceiling and knees bent at 90 degrees above your hips.',
    'Flatten your low back into the floor and keep it there the whole time.',
    'Slowly extend one arm overhead and the opposite leg out long while breathing out fully.',
    'Bring them back to the start, then repeat with the other arm and leg.',
  ],
  crunch: [
    'Lie on your back with knees bent, feet flat, and fingertips resting lightly behind your head.',
    'Breathe out and curl your ribs toward your hips, lifting your shoulder blades off the mat.',
    'Pause briefly at the top without pulling on your neck.',
    'Lower your shoulders slowly back down and repeat.',
  ],
  'jackknife-sit-up': [
    'Lie flat on your back with legs straight and arms stretched overhead on the floor.',
    'Lift your arms and legs together, folding at the hips so your hands meet your shins or feet over your hips.',
    'Lower your arms and legs slowly back toward the floor.',
    'Stop just before touching down and repeat. Bend your knees if your lower back arches.',
  ],
  'reverse-crunch': [
    'Lie on your back with your arms by your sides and your knees bent, feet lifted off the floor.',
    'Use your abs to curl your hips off the floor, bringing your knees in toward your chest.',
    'Pause briefly with your lower back lifted.',
    'Lower your hips slowly back down until your feet hover just off the floor.',
  ],
  'russian-twist': [
    'Sit on the mat with knees bent and lean back slightly, keeping your spine long.',
    'Clasp your hands in front of your chest and lift your feet if you want it harder.',
    'Turn your ribs and hands to one side, then rotate through the middle to the other side.',
    'Keep alternating sides, counting each turn, until the set is done.',
  ],
  'barbell-back-squat': [
    'Set the bar in a rack at chest height, step under it so it rests across your upper back and grip just outside your shoulders.',
    'Stand to lift it off, step back, and set your feet about shoulder width with toes slightly out.',
    'Brace and sit down between your heels, knees tracking over your toes, until your thighs reach about parallel.',
    'Drive up through your mid foot to stand tall. Walk the bar back into the rack when finished.',
  ],
  'barbell-deadlift': [
    'Stand with your feet about hip width and the bar over the middle of your feet.',
    'Hinge and bend your knees to grip the bar just outside your legs, shins touching it, back flat and chest up.',
    'Push the floor away to stand up, keeping the bar close, and finish by squeezing your glutes without leaning back.',
    'Lower the bar back to the floor by pushing your hips back first, then bending your knees.',
  ],
  'barbell-romanian-deadlift': [
    'Stand tall holding a barbell at your thighs, hands just outside your legs and feet hip width.',
    'Soften your knees and push your hips back, sliding the bar down your thighs.',
    'Lower until your hamstrings feel stretched, keeping your back flat and the bar close.',
    'Drive your hips forward to stand back up, squeezing your glutes at the top.',
  ],
  'barbell-hip-thrust': [
    'Sit on the floor with your upper back against the edge of a bench and a padded barbell across your hips.',
    'Plant your feet flat about hip width, tuck your chin and keep your ribs down.',
    'Drive through your heels to lift your hips until your body is flat from knees to shoulders, squeezing your glutes hard.',
    'Lower your hips under control until they nearly touch the floor, then repeat.',
  ],
  'barbell-calf-raise': [
    'Unrack a barbell onto your upper back and step forward to stand with the balls of your feet on a weight plate.',
    'Keep your knees straight and let your heels sink below the plate for a full stretch.',
    'Push up onto your toes as high as you can and pause at the top.',
    'Lower your heels slowly back down, and return the bar to the rack when you finish.',
  ],
  'barbell-bench-press': [
    'Lie on the bench with your eyes under the bar, feet flat, and shoulder blades squeezed together.',
    'Grip the bar a little wider than your shoulders and lift it out of the rack over your chest.',
    'Lower the bar to your mid-chest with elbows about 45 degrees from your body, then press it back up.',
    'Rack the bar when the set is done, and use a spotter or safety bars near failure.',
  ],
  'incline-barbell-bench-press': [
    'Set the bench to a moderate incline, lie back under the rack and grip the bar slightly wider than shoulder width.',
    'Pull your shoulder blades back and down, then unrack the bar over your upper chest.',
    'Lower the bar to your upper chest, then press it back up until your arms are straight.',
    'Finish the set and guide the bar back into the hooks.',
  ],
  'close-grip-barbell-bench-press': [
    'Lie on a flat bench under the racked bar and grip it with your hands about shoulder width.',
    'Unrack the bar and hold it over your chest with your arms straight.',
    'Lower the bar to your lower chest, keeping your elbows tucked close to your sides.',
    'Press the bar back up to straight arms, then rack it after the last rep.',
  ],
  'barbell-overhead-press': [
    'Set the bar at upper-chest height in the rack, grip it just outside your shoulders, and step back with feet hip width.',
    'Squeeze your glutes and brace your core with the bar resting on your upper chest.',
    'Press the bar straight up, moving your head back then forward under it as it passes your face.',
    'Lower the bar under control back to your upper chest and repeat.',
  ],
  'barbell-bent-over-row': [
    'Stand holding a barbell with an overhand grip slightly wider than your shoulders.',
    'Hinge at the hips until your torso is about 45 degrees, back flat and knees slightly bent.',
    'Pull the bar to your lower ribs, keeping your torso still.',
    'Lower it until your arms are straight, then repeat.',
  ],
  'barbell-curl': [
    'Stand tall holding a barbell with an underhand grip at about shoulder width, arms straight.',
    'Keep your elbows at your sides and curl the bar up toward your shoulders.',
    'Squeeze at the top without letting your elbows drift forward or your body lean back.',
    'Lower the bar slowly until your arms are fully straight.',
  ],
  'barbell-shrug': [
    'Stand tall holding a barbell in front of your thighs, hands about shoulder width apart.',
    'Lift your shoulders straight up toward your ears, keeping your arms straight.',
    'Hold the top for a moment without rolling your shoulders.',
    'Lower your shoulders slowly back down and repeat.',
  ],
  'sumo-deadlift': [
    'Stand with feet wide and toes turned out, shins close to the bar.',
    'Squat down and grip the bar with hands inside your knees, chest up and back flat.',
    'Push your knees out and drive through your feet to stand up, finishing tall with your glutes squeezed.',
    'Lower the bar back to the floor under control, keeping it close to your body.',
  ],
  'barbell-good-morning': [
    'Set a light barbell across your upper back from the rack and stand with your feet hip width.',
    'With a slight bend in your knees, push your hips back and tip your chest forward, back flat.',
    'Stop when you feel a strong stretch in your hamstrings.',
    'Drive your hips forward to stand back up tall, then rack the bar when you finish.',
  ],
  'barbell-glute-bridge': [
    'Sit on the mat with your legs straight and roll a padded barbell over your legs until it rests across your hips.',
    'Lie back, bend your knees and plant your feet flat, holding the bar in place with both hands.',
    'Drive through your heels to lift your hips until your body is straight from knees to shoulders, squeezing your glutes.',
    'Keep your ribs down at the top, then lower your hips slowly to the mat.',
  ],
  'barbell-walking-lunge': [
    'Unrack a barbell onto your upper back, step clear of the rack and stand tall with eyes forward.',
    'Take a long step forward and lower until your back knee nearly touches the floor.',
    'Drive through your front heel to stand and bring your back foot through into the next step.',
    'Continue walking forward, alternating legs each rep, then return the bar to the rack.',
  ],
  'barbell-step-up': [
    'Unrack a barbell onto your upper back and stand facing a sturdy bench or box.',
    'Place one whole foot on the bench.',
    'Push through that foot to stand up on the bench, without pushing off the back foot.',
    'Step back down slowly with the same foot first. Finish the set, then switch legs.',
  ],
  'decline-barbell-bench-press': [
    'Lie on a decline bench with your feet locked under the pads and your eyes under the bar.',
    'Grip the bar a little wider than your shoulders and lift it out of the rack.',
    'Lower the bar to your lower chest under control, then press it back up to straight arms.',
    'Rack the bar when done, and use a spotter or safety bars near failure.',
  ],
  'barbell-upright-row': [
    'Stand tall holding a barbell in front of your thighs with an overhand grip wider than your shoulders.',
    'Lead with your elbows to pull the bar up along your body.',
    'Stop when the bar reaches chest height and your elbows are about shoulder level.',
    'Lower the bar slowly back to your thighs. Skip this movement if your shoulders pinch.',
  ],
  'barbell-rear-delt-row': [
    'Hold a light barbell with a wide overhand grip and hinge forward until your torso is close to parallel with the floor.',
    'Let the bar hang straight down with your back flat.',
    'Pull the bar toward your upper chest, flaring your elbows out wide.',
    'Lower the bar slowly until your arms are straight again.',
  ],
  'reverse-grip-barbell-row': [
    'Hold a barbell with palms facing up, hands about shoulder width, and stand with feet hip width.',
    'Bend your knees slightly and hinge forward to about 45 degrees with a flat back.',
    'Row the bar to your belly button, keeping your elbows close to your body.',
    'Lower the bar slowly until your arms are straight, holding the same hinge.',
  ],
  'ez-bar-curl': [
    'Stand tall holding an EZ bar on the angled grips with palms facing up, arms straight.',
    'Keep your elbows pinned at your sides and curl the bar up toward your shoulders.',
    'Squeeze your biceps briefly at the top.',
    'Lower the bar slowly until your arms are fully straight.',
  ],
  'ez-bar-skull-crusher': [
    'Lie on a flat bench holding an EZ bar on the angled grips with your arms straight above your chest.',
    'Keep your upper arms still and bend your elbows to lower the bar toward your forehead or just behind it.',
    'Straighten your elbows to press the bar back up.',
    'Stop with your arms straight above your chest, then repeat.',
  ],
  'barbell-overhead-triceps-extension': [
    'Stand tall and press a barbell overhead with a grip about shoulder width.',
    'Keep your ribs down and your elbows pointing up and close to your head.',
    'Bend your elbows to lower the bar behind your head until you feel a deep stretch.',
    'Straighten your arms to press the bar back overhead, keeping your upper arms still.',
  ],
  'reverse-barbell-curl': [
    'Stand tall holding a barbell in front of your thighs with an overhand grip about shoulder width.',
    'Keep your elbows pinned at your sides and wrists straight as you curl the bar up toward your shoulders.',
    'Pause briefly at the top without letting your elbows drift forward.',
    'Lower the bar slowly until your arms are straight.',
  ],
};
